### ISSUE TITLE
Crash with error message read: interrupted system call

### ISSUE THREAD

**Issue by peterhellberg** [cespare/reflex#22]
## How to reproduce

Rapidly save changes to a file, reflex crashes fairly soon (After 5-10 saves).

### Error message
```bash
read: interrupted system call
```
### Expected behavior

Reflex shouldn’t crash on interrupted system calls

### Environment
                                |   Value
---------------------------|---------------------------------------------------------------
**OS**                      | Debian GNU/Linux 7 (wheezy)
**Architecture**       | i386
**Go version**         | 1.4
**Hosting provider** | [BlueVM](https://www.bluevm.com/)

**Comment by tv42** [comment]
@peterhellberg What kernel version is this? Is this BlueVM OpenVZ, KVM, or what? Can you reproduce outside of BlueVM?

**Comment by peterhellberg** [comment]
Not sure about the specifics since it isn’t my machine (It is a shared
machine, tilde.red)

Kernel is 3.2.0-4-686-pae (gcc version 4.6.3, Debian)

Paravirtualized kernel on KVM

I’ve not seen the issue outside of that VM.

On Tuesday, January 6, 2015, Tv <notifications@github.com> wrote:

> @peterhellberg <https://github.com/peterhellberg> What kernel version is
> this? Is this BlueVM OpenVZ, KVM, or what? Can you reproduce outside of
> BlueVM?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cespare/reflex/issues/22#issuecomment-68810946>.
>


-- 

--
Peter Hellberg
Ruby Developer, Code7 Interactive

**Comment by tv42** [comment]
3.2, as in January 2012? Yeah, that's old enough to still have this (fixed in v3.8): 

```
commit 1ca39ab9d21ac93f94b9e3eb364ea9a5cf2aba06
Author: Eric Paris <eparis@redhat.com>
Date:   2012-03-26 13:07:59 -0400

    inotify: automatically restart syscalls
    
    We were mistakenly returning EINTR when we found an outstanding signal.
    Instead we should returen ERESTARTSYS and allow the kernel to handle
    things the right way.
    
    Patch-from: Oleg Nesterov <oleg@redhat.com>
    Signed-off-by: Eric Paris <eparis@redhat.com>

diff --git a/fs/notify/inotify/inotify_user.c b/fs/notify/inotify/inotify_user.c
index a6879d1..463e828 100644
--- a/fs/notify/inotify/inotify_user.c
+++ b/fs/notify/inotify/inotify_user.c
@@ -264,7 +264,7 @@ static ssize_t inotify_read(struct file *file, char __user *buf,
                ret = -EAGAIN;
                if (file->f_flags & O_NONBLOCK)
                        break;
-               ret = -EINTR;
+               ret = -ERESTARTSYS;
                if (signal_pending(current))
                        break;
 
```

http://lists.openwall.net/linux-kernel/2012/02/10/351

**Comment by peterhellberg** [comment]
Ok, then we can probably consider this issue as solved. Thank you for
looking into it.

On Tuesday, January 6, 2015, Tv <notifications@github.com> wrote:

> 3.2, as in January 2012? Yeah, that's old enough to still have this (fixed
> in v3.8):
>
> commit 1ca39ab9d21ac93f94b9e3eb364ea9a5cf2aba06
> Author: Eric Paris <eparis@redhat.com <javascript:_e(%7B%7D,'cvml','eparis@redhat.com');>>
> Date:   2012-03-26 13:07:59 -0400
>
>     inotify: automatically restart syscalls
>
>     We were mistakenly returning EINTR when we found an outstanding signal.
>     Instead we should returen ERESTARTSYS and allow the kernel to handle
>     things the right way.
>
>     Patch-from: Oleg Nesterov <oleg@redhat.com <javascript:_e(%7B%7D,'cvml','oleg@redhat.com');>>
>     Signed-off-by: Eric Paris <eparis@redhat.com <javascript:_e(%7B%7D,'cvml','eparis@redhat.com');>>
>
> diff --git a/fs/notify/inotify/inotify_user.c b/fs/notify/inotify/inotify_user.c
> index a6879d1..463e828 100644
> --- a/fs/notify/inotify/inotify_user.c
> +++ b/fs/notify/inotify/inotify_user.c
> @@ -264,7 +264,7 @@ static ssize_t inotify_read(struct file *file, char __user *buf,
>                 ret = -EAGAIN;
>                 if (file->f_flags & O_NONBLOCK)
>                         break;
> -               ret = -EINTR;
> +               ret = -ERESTARTSYS;
>                 if (signal_pending(current))
>                         break;
>
>
> http://lists.openwall.net/linux-kernel/2012/02/10/351
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cespare/reflex/issues/22#issuecomment-68813185>.
>


-- 

--
Peter Hellberg
Ruby Developer, Code7 Interactive

**Comment by cespare** [comment]
Thanks for the help @tv42. I'll go ahead and close this for now.

@peterhellberg I'm curious -- can you reproduce this using inotifywait(1)?

**Comment by peterhellberg** [comment]
@cespare No, it *does not* crash when running `./inotifywait --monitor test.txt` with `while true; do echo asdf >> test.txt; done`
