### ISSUE TITLE
-bash: reflex: command not found

### ISSUE THREAD

**Issue by cbrwizard** [cespare/reflex#26]
Hey, I am new to Go so don't blame me for asking a silly question [:
This is probably even not entirely related to reflex, but to any Go package.
I have installed reflex using `go get github.com/cespare/reflex` and it worked. But when I reopened terminal it stopped working and it returns `-bash: reflex: command not found` when I enter `reflex` in a terminal. Writing `go get github.com/cespare/reflex` once again does nothing. Should I set a path correctly or something?

**Comment by cbrwizard** [comment]
Found it, I should have added 
`export PATH=$PATH:$HOME/bin/`
to my .bash_profile

**Comment by cespare** [comment]
Glad you figured it out :)

**Comment by longkeng** [comment]
command not found. shit

**Comment by vanhunguet** [comment]
you can try install reflex
sudo apt install reflex
with ubuntu

**Comment by samarthgowda96** [comment]
My path is been set, all the other commands are working. This is still throwing `err: cmd not found`

**Comment by NoFacePeace** [comment]
感谢您的来信，我尽快回复您！
