### ISSUE TITLE
Entr

### ISSUE THREAD

**Issue by wildeyes** [cespare/reflex#37]
Hello, there is a similar program called [Entr](http://entrproject.org/), I think it would be helpful to do some comparisons and explain why reflex was made and how it is different / better than Entr.

**Comment by lervag** [comment]
I agree; I also think one should add Entr to the list of competition.

**Comment by cespare** [comment]
Feel free to send a PR adding a link to entr to the list.

**Comment by cespare** [comment]
Fixed in #53.

**Comment by tv42** [comment]
It seems like this issue was fixed in 2018 but never got closed.

**Comment by cespare** [comment]
I don't intend to do anything here, so closing.

FWIW I wasn't aware of entr when I wrote reflex (that project was fairly new at the time). I haven't used it, but it looks pretty nice. If it fits your needs, please use it! I'm not trying to recruit users for reflex (and I hardly use it myself).
