### ISSUE TITLE
Trigger events only on file contents changing

### ISSUE THREAD

**Issue by myitcv** [cespare/reflex#47]
Raising this here for discussion (because I use `reflex` extensively and would welcome thoughts on the thinking).

In [this CL](https://go-review.googlesource.com/c/tools/+/106675) I proposed updating `stringer` to only write to its output file if the contents changed.

But @mvdan [pointed out](https://go-review.googlesource.com/c/tools/+/106675#message-64c14054fc891144330bc4a0e8dd55e6330aa321) that to do so would break the isolation rule Russ mentions in https://github.com/golang/go/issues/24356#issuecomment-376302665

Could we therefore have `reflex` operate in a mode where it only fires events when the contents of a file have changed?

**Comment by cespare** [comment]
Seems like a fairly niche use case. You could also work around this by ignoring the output files of stringer.

I wonder if we should try to detect infinite loops and exit or print a warning or something, though.

**Comment by myitcv** [comment]
> You could also work around this by ignoring the output files of stringer.

You could, yes, but then you would also need to add rules to ignore the output files of all the other code generators you also use, and do so everywhere you use `reflex`. The list of exceptions would start to get unwieldy, as, I suspect, would the edge cases.

I've implemented this in another watcher in case you think this doesn't belong in `reflex`. So I'll close this issue for now.

Thanks
