### ISSUE TITLE
"too many open files" error

### ISSUE THREAD

**Issue by jgoodall** [cespare/reflex#6]
When I run a `reflex` command within my $GOPATH, I get a bunch of errors related to "too many open files". Here is an example:

```
[info] Error while watching new path src/code.google.com/p/go.net/websocket: open src/code.google.com/p/go.net/websocket: too many open files
```

I am on Mac OS X 10.9. I installed with `go get` (and then moved the binary into my ~/bin). I can run reflex in other directories that only have a few files. Here is the reflex command I am running:

```
reflex -g '*.go' -- go test github.com/jgoodall/test
```

It actually doesnt seem to matter what the command is, I get the same errors.

**Comment by danawoodman** [comment]
`-R ".git"` was the fix for me 👍
