### ISSUE TITLE
Running reflex in Docker

### ISSUE THREAD

**Issue by NedkoHristov** [cespare/reflex#60]
Does someone do a multi stage builds with Reflex? I would like to keep the container size as low as possible.
I've try to find some implementation, but without success.

**Comment by NedkoHristov** [comment]
Seems that I didn't search as much as I though, sorry for the created issue.

https://github.com/Its-Alex/docker-alpine-reflex/blob/master/Dockerfile

**Comment by AlonzoRicardo** [comment]
Do you have working example of reflex working with volumes?, what i'm trying to achieve is having a container running my go program rebuild every time reflex finds changes in the source code on the host.

**Comment by adonespitogo** [comment]
> Do you have working example of reflex working with volumes?, what i'm trying to achieve is having a container running my go program rebuild every time reflex finds changes in the source code on the host.

@AlonzoRicardo have you figured it out? I want to do the same, but reflex isn't detecting the changes in my docker container.

**Comment by NoFacePeace** [comment]
感谢您的来信，我尽快回复您！
