### ISSUE TITLE
Not installing in macOS 10.14.5

### ISSUE THREAD

**Issue by gnpan** [cespare/reflex#64]
macOS 10.14.5, go 1.12.7
Using `go get github.com/cespare/reflex` does nothing.

**Comment by gnpan** [comment]
Sorry, it's there, just not where I expected (it goes to HOME/go/bin)

**Comment by akcgjc007** [comment]
Where is it then? `reflex` command is still not working?

**Comment by NoFacePeace** [comment]
感谢您的来信，我尽快回复您！

**Comment by cespare** [comment]
You should follow the installation instructions.
