### ISSUE TITLE
Error: Setctty set but Ctty not valid in child

### ISSUE THREAD

**Issue by 9cat** [cespare/reflex#79]
[00] Starting service
[00] fork/exec ./xxxxx.sh: Setctty set but Ctty not valid in child

**Comment by 9cat** [comment]
problem in pty:  https://github.com/creack/pty/issues/96

**Comment by 9cat** [comment]
https://github.com/golang/go/issues/29458

**Comment by cespare** [comment]
This was already fixed in 456b3718abbf1922cfbd498521c27851250f5496 (tagged as v0.3.0).
