### ISSUE TITLE
Any option to remove that `[00]` prefix

### ISSUE THREAD

**Issue by dxps** [cespare/reflex#89]
Hi everyone!

Maybe I missed that if it exists, but I couldn't find an option to get rid of `[00] ` "prefix" that I get on each line.
I know it shows which shell - if multiple shells (`sh -c "..."`) are being started - returned that output, but if I'm using one single `sh -c ...`, then I don't see the point of keep having it.

Concrete Example

Using `reflex -d fancy -r '\.go' -s -t 1000ms -- sh -c "go run ./cmd/my_app/main.go"`

the output is:

```shell
$ ./run_dev.sh 
[00] Starting service
[00] DEBUG  [2021-12-11T14:43:39+02:00] Repos inited.                                
[00] INFO   [2021-12-11T14:43:39+02:00] Listening for HTTP API requests on port :8181 
[00] DEBUG  [2021-12-11T14:43:39+02:00] Fetched 11589 entries.                       
[00] DEBUG  [2021-12-11T14:43:41+02:00] Synced listings in 2.153454605 seconds. 
```

I'm a big fan of this tool, it works great for my needs, and I want to keep using it.
Thanks for doing it! :pray:

**Comment by gabroo** [comment]
https://github.com/cespare/reflex#:~:text=%2Dd%2C%20%2D%2Ddecoration%3D%22plain%22%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20How%20to%20decorate%20command%20output.%20Choices%3A%20none%2C%20plain%2C%20fancy.

you have to use `reflex -d none ...` to remove the prefix

**Comment by gabroo** [comment]
you have to use `reflex -d none ...` to remove the prefix

**Comment by dxps** [comment]
Indeed! Thanks a lot @gabroo! :pray:
