### ISSUE TITLE
Command not found on Mac 13.0

### ISSUE THREAD

**Issue by Smahrt** [cespare/reflex#93]
I installed reflex with 

```
go get github.com/cespare/reflex
``` 

but when I run 

```
reflex
```

I get this error:

```
zsh: command not found: reflex
```
and
```
/bin/sh: command not found: reflex
```

on zsh and bash respectively. I have added `export PATH=$PATH:$HOME/bin` to my path but still get the same error.

**Comment by cespare** [comment]
Please follow the installation instructions in the readme.
