### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by UIT-AnhTu-0325** [cespare/reflex#96]
I have add line  `RUN go get github.com/cespare/reflex` to Dockerfile 
![image](https://user-images.githubusercontent.com/71314673/233032921-ba460b0a-a7e3-454b-9b13-f265d9b22733.png)
After that, i use command `command: reflex -r "\.go$$" -s -- sh -c "go run ./"` in docker-compose.yml
![image](https://user-images.githubusercontent.com/71314673/233033111-fcee7695-2875-405f-935c-a885dda23afb.png)

But when I run `docker-compose up --build` there are an error when running the command
_Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "reflex": executable file not found in $PATH: unknown_
![image](https://user-images.githubusercontent.com/71314673/233033526-c3f125a0-d345-425d-8e6d-af35fa48c808.png)

I'm using Window 10 and Go 1.20

Can someone check it for me pls, thanks!

**Comment by NoFacePeace** [comment]
感谢您的来信，我尽快回复您！

**Comment by cespare** [comment]
Sorry, but this seems like a docker/docker-compose issue; nothing to do with reflex as far as I can see.
